### ISSUE TITLE
Unused Services Panorama.

### ISSUE THREAD

**Issue by AJDiaz86** [PaloAltoNetworks-BD/pan-configurator#1]
Hi, I had been working on Panorama migrating rules from Juniper to palo alto, but now I´m having an issue with the number of services I can create, I reached the limit and now I don't know how to check how many services are unused, is there any option or script to check which services are unused to delete?

I have 2000 services and 5000 rules.

Thanks in advance.. 

A.J.

**Comment by cpainchaud** [comment]
Quick questions :
1/ are you limited on the local firewall or is it Panorama that is not allowing you to create more than 2000 service objects ?
2/ Did you disable the option "Push unused objects to firewalls" in Panorama? (ignore if not relevant)

**Comment by AJDiaz86** [comment]
I'm limited by Panorama, and yes "Push unused objects to firewalls" is disable, I'm trying to find a way to check which services are unused to delete, something similar to panorama-unused-objects.php.

**Comment by cpainchaud** [comment]
Ok, last question : can objects be used in local firewalls rules? ( firewall local rules using objects from Panorama). If yes then I have no script ready to run/stable. I didn't have time to make a proper and standard one.

If not then you guessed right : panorama-unused-objects.php can be adapted ( 5 lines to be changed at first look ) to spot unused services instead of unused Address objects.

**Comment by AJDiaz86** [comment]
Sorry, I was wrong, I'm limited by the local firewall, in Panorama I have more than 2000 services but in palo alto I can use only 2000, I'm checking again and I'm trying to find the number of unused services in the local firewall.

**Comment by cpainchaud** [comment]
Ok, so in first instance you said that you disabled option ""Push unused objects to firewalls"" , can you double confirm ?

If it's already disabled then unfortunately it means that your firewall is using all these groups and you can do nothing (simple) about it but to delete/explode some. You could use my library to check for groups with little use (referenced in less than 2/3 rules) and 'explode' them : use their members instead of the group itself in the rules.

If it's not disabled then please disable it and retry to push config , it's made for that purpose.

**Comment by AJDiaz86** [comment]
It is disable, I'll try to check groups with litlle use as you said...

Thanks.

**Comment by cpainchaud** [comment]
You should modify the example where-used script to just print the number of references or print a special message when they are < 3 and then see where it leads you.

object->countReferences() is the way to know how many times this object is used.

**Comment by cpainchaud** [comment]
I made a script called 'service-edit.php' that you could eventually use to spot groups you are looking for.
just get latest version.

cheers

**Comment by AJDiaz86** [comment]
I'll try it now !

Thank you !
